### ISSUE TITLE
Нет запятых!!!!

### ISSUE THREAD

**Issue by megaSmartGuyThatKnowWhereShouldBeComas** [lenchv/bsa2017_task1#1]
Пропущены знаки препинания в статье, читать невозможно !!!!

**Comment by lenchv** [comment]
@megaSmartGuyThatKnowWhereShouldBeComas, в ветке [edit](https://github.com/lenchv/bsa2017_task1/tree/edit) норм?

**Comment by megaSmartGuyThatKnowWhereShouldBeComas** [comment]
@lenchv , норм

**Comment by lenchv** [comment]
@megaSmartGuyThatKnowWhereShouldBeComas , перенес в основную ветку

**Comment by megaSmartGuyThatKnowWhereShouldBeComas** [comment]
@lenchv, четко
