### ISSUE TITLE
Абзац в одной строке

### ISSUE THREAD

**Issue by GuyThatLovelyMultilines** [lenchv/bsa2017_task1#2]
Каждый абзац в одной строке, сложно отслеживать изменения, разбейте построчно, пожалуйста.

**Comment by lenchv** [comment]
@GuyThatLovelyMultilines , пофиксим

**Comment by GuyThatLovelyMultilines** [comment]
Спасибо, можно закрывать. Я добавил в ветку [video ](https://github.com/lenchv/bsa2017_task1/tree/video) ссылку на youtube с видео по теме.

**Comment by lenchv** [comment]
@GuyThatLovelyMultilines , окей, добавлю в главную ветку
