### ISSUE TITLE
Hi-res image

### ISSUE THREAD

**Issue by volodymyr-kushnir** [lenchv/bsa2017_task1#3]
Hey, you're doing amazingly great. Pleasure to read.
May I suggest adding a full-width hi-res image? I would create a PR for you myself, but am a bit busy now, so could you please:
1) do a separate branch with something like this `<a href="https://www.youtube.com/watch?v=j-Vz38ECJh0"><img width="100%" src="https://i.ytimg.com/vi/j-Vz38ECJh0/hq720.jpg" /></a>`  instead of your current link,
2) create a pull request for yourself and merge it?

Thanks so much!

*P. S. Oh yeah, and please use "Fixes #3" as your commit message to autoclose this issue.*

**Comment by lenchv** [comment]
@volodymyr-kushnir , thanks, did it =)
